FROM golang:1.17

WORKDIR /app
COPY . /app

ENV GRPC_SERVER_CLIENT_ADDR_SELF="0.0.0.0"
ENV GRPC_SERVER_CLIENT_PORT_SELF="8080"
ENV WEEKSDB_SERVER_ADDR_AND_PORT="placeholder"

RUN go build main.go
ENTRYPOINT ["./main"]